### ISSUE TITLE
How use

### ISSUE THREAD

**Issue by tecnolive** [iJKCode/hass-switchbot-hub#1]
i installed with this plugin, but how do i use it? The devices are not shown anywhere.

**Comment by iJKCode** [comment]
You add the plugin manually or using hacs.
Then you can go to configuration -> devices & services -> add integration -> switchbot hub (it does not have an icon).
Click it and enter your switchbot API key, I believe you can find your key somewhere in the app (not sure though).
Then your devices show up as entities which you can add to your dashboard.

Some caveats:
- This plugins uses the switchbot api instead of a direct bluetooth/ble connection. A friend of mine is not able to use bluetooth, thus I wrote this plugin.
- This plugin only supports the curtain bot and the temperature/humidity meter (My friend does not have any others to test).
- You need a switchbot hub to bridge your switchbot devices to the cloud.
- Switchbot has a daily api request limit of 10000 requests, this plugin has a polling interval of 1 minute so 6 devices is the maximum (8640 req/day) leaving 1360 requests per day for actions (open/close curtains).

I really recommend you to use the official switchbot plugin (built into hass).
It is more responsive since it directly connects to the switchbot devices instead of through the cloud.
You can add it using the "add integration" button as well, though your hass device needs ble/bluetooth support to use the official plugin.

**Comment by tecnolive** [comment]
Thanks for the reply. 

With your integration is possible manage switchbot hub mini for climate control?

thanks.

**Comment by iJKCode** [comment]
That depends on your specific situation.
You can use the switchbot hub mini in combination with a switchbot meter to read the temperature/humidity and then use a different integration to control AC/Heating.

This integration only supports reading the temperature and humidity from the switchbot meter and opening/closing curtains and reading their current position.
Other switchbot devices/operations are not supported.
